## 6.No Exception Authorized
- We have a few options to remove exceptions
    - Use Hollywood principle -> callback functions `onSuccess`, `onFailure`
    - Use a data structure representing computation results : `success` or `failure`
- We have already used such a type : `ConversionResult`
    - Let's iterate on it

### Portfolio
- We start, as usual, with a red test at the `Portfolio` level
    - We rename the `evaluate` method into `evaluateWithException`

```java
@Test
@DisplayName("Return a failure result in case of missing exchange rates")
void shouldReturnAFailingResultInCaseOfMissingExchangeRates() {
    var portfolio = portfolioWith(
            euros(1),
            dollars(1),
            koreanWons(1)
    );

    assertThat(portfolio.evaluate(bank, EUR)
            .failure())
            .isEqualTo("Missing exchange rate(s): [USD->EUR],[KRW->EUR]");
}
```

- We generate `evaluate` method from the test
    - We need to change `ConversionResult` accessibility as well
- Let's implement the `evaluate` by calling the old one first
- We need to adapt the `ConversionResult` to support another `Exception` type
    - Let's this type supports a Generic Failure
- We need to adapt our `Portfolio` to use the Generic type everywhere
- Our test is now green
- Let's refactor
    - We implement the new evaluation logic
        - Because we will have to change method signature we choose to duplicate the code
- Let's adapt a first test to use new `evaluate` method
    - Code is no longer throwing `Exception`
    - We need to access `money()` from `ConversionResult`
- We can now remove dead code and duplication
    - Method `evaluateWithException` is no longer used
        - Its related private methods as well : `toMissingExchangeRatesException`, `toMoney`
    - The `MissingExchangeRatesException` can be deleted as well

- We can make some clean up:
    - Extract inner public class in its own file
    - Extract some methods from the `evaluate` one
- We may express success and failure in more visual way : `fromFailure`, `fromSuccess` methods
    - Let's refactor it

```java
public record ConversionResult<Failure>(Money money, Failure failure) {
    private ConversionResult(Money money) {
        this(money, null);
    }

    private ConversionResult(Failure exception) {
        this(null, exception);
    }

    public static <F> ConversionResult<F> fromFailure(F failure) {
        return new ConversionResult<>(failure);
    }

    public static <F> ConversionResult<F> fromSuccess(Money money) {
        return new ConversionResult<>(money);
    }

    public boolean isFailure() {
        return failure != null;
    }

    public boolean isSuccess() {
        return money != null;
    }
}
```

- We have already removed 1 `Exception` now we need to do the same at the `Bank` level

### Bank
- Let's start with a red test (failure without throws)
- Let's rename the existing `convert` to `convertWithException` and generate the code from our test
- Make our test green
- Let's refactor
- Adapt our callers to use the new `convert`: `Portfolio` and `BankTest`
    - Really easy in the tests
- We have some work to refactor the `Porftolio`
    - We start by changing the `convertAllMoneys` method
- We adapt methods in `Portfolio` to only use `ConversionResult<String>`
- We can now remove the `convertWithException` method in `Bank` and `MissingExchangeRateException`

## Reflect
`What can be still improved?`

- The way we use the `ConversionResult` is not safe for example...
- Maybe there is an alternative to use safer data structure
- You can discover more about the `Monad` concepts and how to apply them in java with [vavr](https://www.vavr.io/)